brasileirao2026dia0604=('Palmeiras', 'São Paulo', 'Fluminense', 'Flamengo','Bahia', 'Athletico-PR', 'Coritiba', 'Atlético-MG','RB Bragantino', 'Botafogo', 'Grêmio', 'Vasco','Internacional','Vitória', 'Santos','Corinthians','Chapecoense','Remo','Cruzeiro', 'Mirassol')
print(f'A lista de times na colocação normal é: {brasileirao2026dia0604}')
print('-='*20)
print(f'os primeiros 5 colocados atualmente são {brasileirao2026dia0604[0:5]}')
print('-='*20)
print(f'Na zona de rebaixamento temos: {brasileirao2026dia0604[16:]}')
print('-='*20)
print(f'Em ordem alfabética temos os times: {sorted(brasileirao2026dia0604)}')
print('-='*20)
print(f'Atualmente o Vasco está na posição {brasileirao2026dia0604.index('Vasco')+1}')